env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  import/prefer-default-export: 0
  import/named: 0
  no-param-reassign: 0
  linebreak-style:
    - error
    - unix
  camelcase: 0
  max-len:
    - error
    - code: 200
